# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'set_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for set_app
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'set_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'set_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
